# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'procon-proj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for procon-proj
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
#  pod 'TesseractOCRiOS'
  
  target 'procon-projTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'procon-projUITests' do
    # Pods for testing
  end

end
